---
DESIGN_NAME: mul_32
VERILOG_FILES: dir::rtl/*.sv
# Power Distribution Stuff
FP_PDN_VOFFSET: 7
FP_PDN_HOFFSET: 7
FP_PDN_SKIPTRIM: true
CLOCK_PERIOD: 1000
CLOCK_PORT: clk
RUN_CTS: false
RUN_KLAYOUT_XOR: false
RUN_POST_GRT_DESIGN_REPAIR: true
DIE_AREA: [0, 200, 0, 200]
